apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kong-watcher-daemonset
  namespace: apim
spec:
  selector:
    matchLabels:
      app: kong-watcher-daemonset
  template:
    metadata:
      labels:
        app: kong-watcher-daemonset
    spec:
      # eBPF XDP 실행을 위한 필수 설정
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      
      # Linux 노드에만 배포
      nodeSelector:
        kubernetes.io/os: linux
      
      # 마스터/컨트롤플레인 노드에도 배포
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: kong-watcher
        image: harbor.ops.action.cloudz.co.kr/apim/kong-watcher:0.0.2
        imagePullPolicy: Always
        
        # eBPF XDP를 위한 특권 모드
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - BPF
            - SYS_RESOURCE
            - SYS_PTRACE
            - DAC_OVERRIDE
            - NET_RAW
            - SYS_MODULE
        
        # eBPF 실행을 위한 필수 볼륨 마운트
        volumeMounts:
        - name: sys-fs-bpf
          mountPath: /sys/fs/bpf
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
        - name: proc
          mountPath: /proc
        - name: dev
          mountPath: /dev
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
      
      # eBPF 실행을 위한 필수 볼륨
      volumes:
      - name: sys-fs-bpf
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: usr-src
        hostPath:
          path: /usr/src
          type: Directory
      
      # 이미지 풀 시크릿
      imagePullSecrets:
      - name: regsecret
